{{- if not .Values.key.existingSecret }}
{{- if not .Values.key.value }}
{{- fail "You must set either key.value or key.existingSecret. Get a key from https://lichess.org/get-fishnet" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fishnet.fullname" . }}
  labels:
    {{- include "fishnet.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.key.secretKey }}: {{ .Values.key.value | quote }}
{{- end }}
